name: First workflow
on: workflow_dispatch
jobs: 
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: print greeting
        run: echo "hello world"
      - name: multi-line greeting
        run: |
         echo "first line"
         echo "second line"
      - name: print goodbye
        run: echo "done - bye"
